version: '3'

volumes:
  pg_foodgram_data_production:
  static_volume:
  media_volume:

services:
  db_foodgram:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_foodgram_data_production:/var/lib/postgresql/data
  backend:
    image: almalina/foodgram_backend:latest
    env_file: .env
    depends_on:
      - db_foodgram
    volumes:
      - static_volume:/backend_static
      - media_volume:/app/media
  frontend:
    image: almalina/foodgram_frontend:latest
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: almalina/foodgram_gateway:latest
    env_file: .env
    depends_on:
      - backend
    volumes:
      - static_volume:/staticfiles/
      - media_volume:/app/media
    ports:
      - 9090:80